# Generated by Django 3.2.9 on 2021-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('picture_url', models.TextField()),
                ('status_message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
