# Generated by Django 3.2.9 on 2021-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.TextField(default='0'),
        ),
    ]
